services:
  clickhouse:
    container_name: clickhouse
    image: bitnami/clickhouse:latest
    restart: always
    env_file: ".env"
    volumes:
      - type: bind
        source: ./data
        target: /bitnami/clickhouse/data
    ports:
      - 8123:8123
      - 9000:9000